lib/rep_web/router.ex
defmodule RepWeb.Router do
  use RepWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RepWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete],
                                              singleton: true
  end

  scope "/addresses", RepWeb do
    pipe_through [:browser, :authenticate_user]

    get "/stops", BreakController, :stops
    get "/incomplete", BreakController, :incomplete
    get "/recent_orders", OrderController, :recent_orders

    resources "/", AddressController do
      resources "/complectations", ComplectationController
      resources "/breaks", BreakController
      resources "/orders", OrderController
    end

  end

  scope "/admin", RepWeb, as: :admin do
    pipe_through [:browser, :authenticate_user, :authenticate_admin]

    resources "/users", UserController
  end

  defp authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn
        |> Phoenix.Controller.put_flash(:error, gettext("Login required"))
        |> Phoenix.Controller.redirect(to: "/")
        |> halt()
      user_id ->
        assign(conn, :current_user, Rep.Accounts.get_user!(user_id))
    end
  end

  defp authenticate_admin(conn, _) do
    case conn.assigns.current_user.credential.is_admin do
      false ->
        conn
        |> Phoenix.Controller.put_flash(:error, gettext("Admin required"))
        |> Phoenix.Controller.redirect(to: "/")
        |> halt()
      true -> conn
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", RepWeb do
  #   pipe_through :api
  # end
end

lib/rep_web/views/layout_view.ex
defmodule RepWeb.LayoutView do
  use RepWeb, :view
end

lib/rep_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= gettext("Lifts") %></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><%= link gettext("Addresses"), to: address_path(@conn, :index) %></li>
            <li><%= link gettext("Stops"), to: break_path(@conn, :stops) %></li>
            <li><%= link gettext("Incomplete"), to: break_path(@conn, :incomplete) %></li>
            <li><%= link gettext("Orders"), to: order_path(@conn, :recent_orders) %></li>
            <li><%= link gettext("Logout"), to: session_path(@conn, :delete), method: :delete  %></li>
          </ul>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>