lib/rep_web/router.ex
defmodule RepWeb.Router do
  use RepWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RepWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete],
                                              singleton: true
  end

  scope "/addresses", RepWeb do
    pipe_through [:browser, :authenticate_user]

    get "/stops", BreakController, :stops
    get "/incomplete", BreakController, :incomplete
    get "/recent_orders", OrderController, :recent_orders

    resources "/", AddressController do
      resources "/complectations", ComplectationController
      resources "/breaks", BreakController
      resources "/orders", OrderController
    end

  end

  scope "/admin", RepWeb, as: :admin do
    pipe_through [:browser, :authenticate_user, :authenticate_admin]

    resources "/users", UserController
  end

  defp authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn
        |> Phoenix.Controller.put_flash(:error, gettext("Login required"))
        |> Phoenix.Controller.redirect(to: "/")
        |> halt()
      user_id ->
        assign(conn, :current_user, Rep.Accounts.get_user!(user_id))
    end
  end

  defp authenticate_admin(conn, _) do
    case conn.assigns.current_user.credential.is_admin do
      false ->
        conn
        |> Phoenix.Controller.put_flash(:error, gettext("Admin required"))
        |> Phoenix.Controller.redirect(to: "/")
        |> halt()
      true -> conn
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", RepWeb do
  #   pipe_through :api
  # end
end

lib/rep_web/controllers/address_controller.ex
defmodule RepWeb.AddressController do
  use RepWeb, :controller

  alias Rep.Lifts
  alias Rep.Lifts.Address

  plug :require_existing_mechanic
  plug :authorize_address when action in [:edit, :update, :delete]

  defp require_existing_mechanic(conn, _) do
    mechanic = Lifts.ensure_mechanic_exists(conn.assigns.current_user)
    assign(conn, :current_mechanic, mechanic)
  end

  defp authorize_address(conn, _) do
    address = Lifts.get_address!(conn.params["id"])

    if conn.assigns.current_mechanic.id == address.mechanic_id do
      assign(conn, :address, address)
    else
      conn
      |> put_flash(:error, "You can't modify that address")
      |> redirect(to: address_path(conn, :index))
      |> halt()
    end
  end

  def index(conn, _params) do
    addresses = Lifts.list_addresses(conn.assigns.current_mechanic)
    render(conn, "index.html", addresses: addresses)
  end

  def new(conn, _params) do
    changeset = Lifts.change_address(%Address{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"address" => address_params}) do
    case Lifts.create_address(conn.assigns.current_mechanic, address_params) do
      {:ok, address} ->
        conn
        |> put_flash(:info, gettext("Address created successfully."))
        |> redirect(to: address_path(conn, :show, address))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    address = Lifts.get_address!(id)
    breaks = Lifts.list_breaks(address)
    orders = Lifts.list_orders(address)
    complectations = Lifts.list_complectations(address)
    render(conn, "show.html", address: address, breaks: breaks, orders: orders, complectations: complectations)
  end

  def edit(conn, %{"id" => id}) do
    address = Lifts.get_address!(id)
    changeset = Lifts.change_address(address)
    render(conn, "edit.html", address: address, changeset: changeset)
  end

  def update(conn, %{"address" => address_params}) do
    case Lifts.update_address(conn.assigns.address, address_params) do
      {:ok, address} ->
        conn
        |> put_flash(:info, gettext("Address updated successfully."))
        |> redirect(to: address_path(conn, :show, address))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  def delete(conn, _) do
    {:ok, _address} = Lifts.delete_address(conn.assigns.address)

    conn
    |> put_flash(:info, gettext("Address deleted successfully."))
    |> redirect(to: address_path(conn, :index))
  end

end

lib/rep_web/views/address_view.ex
defmodule RepWeb.AddressView do
  use RepWeb, :view

  def to_date dt do
    dt
    |> Date.to_string
    |> String.split("-")
    |> Enum.reverse
    |> Enum.join("/")
  end
end

lib/rep_web/templates/address/edit.html.eex
<h2><%= gettext "Edit Address" %></h2>

<%= render "form.html", Map.put(assigns, :action, address_path(@conn, :update, @address)) %>

<span><%= link gettext("Cancel"), to: address_path(@conn, :index) %></span>

lib/rep_web/templates/address/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p><%= gettext "Oops, something went wrong! Please check the errors below." %></p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, gettext("Street"), class: "control-label" %>
    <%= text_input f, :street, class: "form-control" %>
    <%= error_tag f, :street %>
  </div>

  <div class="form-group">
    <%= label f, gettext("House"), class: "control-label" %>
    <%= text_input f, :house, class: "form-control" %>
    <%= error_tag f, :house %>
  </div>

  <div class="form-group">
    <%= label f, gettext("Entrance"), class: "control-label" %>
    <%= text_input f, :entrance, class: "form-control" %>
    <%= error_tag f, :entrance %>
  </div>

  <div class="form-group">
    <%= label f, gettext("Notes"), class: "control-label" %>
    <%= text_input f, :notes, class: "form-control" %>
    <%= error_tag f, :notes %>
  </div>

  <div class="form-group">
    <%= submit gettext("Submit"), class: "btn btn-primary" %>
  </div>
<% end %>

lib/rep_web/templates/address/index.html.eex
<h2><%= gettext "Addresses" %></h2>

<table class="table">
  <thead>
    <tr>
      <th><%= gettext "Street" %></th>
      <th><%= gettext "House" %></th>
      <th><%= gettext "Entrance" %></th>
      <th><%= gettext "Notes" %></th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for address <- @addresses do %>
    <tr>
      <td><%= address.street %></td>
      <td><%= address.house %></td>
      <td><%= address.entrance %></td>
      <td><%= address.notes %></td>

      <td class="text-right buttons-right">
        <span><%= link " ", to: address_path(@conn, :show, address), class: "btn btn-default btn-xs glyphicon glyphicon-eye-open" %></span>
        <span><%= link " ", to: address_path(@conn, :edit, address), class: "btn btn-default btn-xs glyphicon glyphicon-pencil" %></span>
        <span><%= link " ", to: address_path(@conn, :delete, address), method: :delete, data: [confirm: gettext("Are you sure?")], class: "btn btn-danger btn-xs glyphicon glyphicon-remove" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link gettext("New Address"), to: address_path(@conn, :new) %></span>

lib/rep_web/templates/address/new.html.eex
<h2><%= gettext "New Address" %></h2>

<%= render "form.html", Map.put(assigns, :action, address_path(@conn, :create)) %>

<span><%= link gettext("Cancel"), to: address_path(@conn, :index) %></span>

lib/rep_web/templates/address/show.html.eex
<h2> <%= gettext "Address" %> </h2>
<strong><%= gettext "Street" %>:</strong> <%= @address.street %>,
<strong><%= gettext "House" %>:</strong> <%= @address.house%> <%= @address.entrance %>,
<%= @address.notes %>. &nbsp; &nbsp;
<span><%= link " ", to: address_path(@conn, :edit, @address), class: "btn btn-default btn-xs glyphicon glyphicon-pencil" %></span><br></br>

<h4><%= gettext "Breaks" %></h4>
<table class="table">
  <thead>
    <tr>
      <th><%= gettext "Served" %></th>
      <th><%= gettext "Stoped" %></th>
      <th><%= gettext "Started" %></th>
      <th><%= gettext "Fixed" %></th>
      <th><%= gettext "Notes" %></th>

      <th><%= link " ", to: address_break_path(@conn, :new, @address.id), class: "pull-right btn btn-default btn-xs glyphicon glyphicon-plus" %></th>
    </tr>
  </thead>
  <tbody>
<%= for break <- @breaks do %>
    <tr>
      <td><%= to_date break.served %></td>
      <td><%= if break.stoped, do: "✓", else: "-" %></td>
      <td><%= if break.started, do: "✓", else: "-" %></td>
      <td><%= if break.fixed, do: "✓", else: "-" %></td>
      <td><%= break.notes %></td>

      <td class="text-right buttons-right">
        <span><%= link "", to: address_break_path(@conn, :edit, @address.id, break), class: "btn btn-default btn-xs glyphicon glyphicon-pencil" %></span>
        <span><%= link " ", to: address_break_path(@conn, :delete, @address.id, break), method: :delete, data: [confirm: gettext("Are you sure?")], class: "btn btn-danger btn-xs glyphicon glyphicon-remove" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<h4><%= gettext "Orders" %></h4>
<table class="table">
  <thead>
    <tr>
      <th><%= gettext "Sended" %></th>
      <th><%= gettext "Ordered" %></th>
      <th><%= gettext "Received" %></th>
      <th><%= gettext "Used" %></th>

      <th><%= link " ", to: address_order_path(@conn, :new, @address.id), class: "pull-right btn btn-default btn-xs glyphicon glyphicon-plus" %></th>
    </tr>
  </thead>
  <tbody>
<%= for order <- @orders do %>
    <tr>
      <td><%= to_date order.sended %></td>
      <td><%= order.ordered %></td>
      <td><%= order.received %></td>
      <td><%= order.used %></td>

      <td class="text-right buttons-right">
        <span><%= link "", to: address_order_path(@conn, :edit, @address.id, order), class: "btn btn-default btn-xs glyphicon glyphicon-pencil" %></span>
        <span><%= link " ", to: address_order_path(@conn, :delete, @address.id, order), method: :delete, data: [confirm: gettext("Are you sure?")], class: "btn btn-danger btn-xs glyphicon glyphicon-remove" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<h4><%= gettext "Complectation" %></h4>

<table class="table">
  <thead>
    <tr>
      <th><%= gettext "Station" %></th>
      <th><%= gettext "Floors" %></th>
      <th><%= gettext "Underfloor" %></th>
      <th><%= gettext "Doors" %></th>
      <th><%= gettext "Notes" %></th>

      <th>
        <span><%= link " ", to: address_complectation_path(@conn, :new, @address), class: "pull-right btn btn-default btn-xs glyphicon glyphicon-plus"  %></span>
      </th>
    </tr>
  </thead>
  <tbody>
<%= for complectation <- @complectations do %>
    <tr>
      <td><%= complectation.station %></td>
      <td><%= complectation.floors %></td>
      <td><%= if complectation.underfloor, do: "✓", else: "-" %></td>
      <td><%= complectation.doors %></td>
      <td><%= complectation.notes %></td>

      <td class="text-right buttons-right">
        <span><%= link " ", to: address_complectation_path(@conn, :edit, @address.id, complectation), class: "btn btn-default btn-xs glyphicon glyphicon-pencil" %></span>
        <span><%= link " ", to: address_complectation_path(@conn, :delete, @address.id, complectation), method: :delete, data: [confirm: gettext("Are you sure?")], class: "btn btn-danger btn-xs glyphicon glyphicon-remove" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>